NVIDIA/nvidia-container-toolkit

- CHANGELOG.md
- versions.mk
> chore: Update CUDA base image to 12.3.2

- internal/info/proc/devices/devices.go
Signed-off-by: Tariq Ibrahim <tibrahim@nvidia.com>
(cherry picked from commit f80f4c485d0298a25823035f7366e1e096ddb42e)
> [R550 driver support] add fallback logic to device.Exists(name)

- .golangci.yml
> Add lint exclude for hooks.Prestart deprecation

- pkg/nvcdi/lib.go
This change ensures that nvnllib and devicelib are constructed before these are used to construct infolib.
> Ensure consistent construction order for libs

- docker/Dockerfile.rpm-yum
Includes change from https://github.com/NVIDIA/libnvidia-container/pull/268
> Fix ppcle64 builds

- .common-ci.yml
- .nvidia-ci.yml
Auto siging of gpu-operator released images @cdesiniotis
> add ngc image signing job for auto signing

- tools/container/nvidia-toolkit/run.go
- tools/container/toolkit/toolkit.go
This change makes the following changes:
* Allows the toolkit.pid path to be specified
* Creates the toolkit.pid file at /run/nvidia/toolkit/toolkit.pid by default
* Handles failures to remove the /run/nvidia/toolkit folder
> Allow toolkit.pid path to be specified

- internal/discover/graphics.go
Reverts NVIDIA/nvidia-container-toolkit#490
> Revert "Inject additional libraries required for full display functionality"

- .github/workflows/release.yaml
- CHANGELOG.md
- hack/generate-changelog.sh
Additional changes for the v1.16.0-rc.1 release.
See also #545
> Bump v1.16.0 rc.1

- cmd/nvidia-container-runtime-hook/main.go
- cmd/nvidia-ctk/cdi/generate/generate.go
- internal/config/features.go
- internal/discover/ipc.go
- internal/modifier/cdi.go
- internal/modifier/gated.go
- pkg/nvcdi/common-nvml.go
- pkg/nvcdi/driver-nvml.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/management.go
- pkg/nvcdi/options.go
- tools/container/toolkit/toolkit.go
This change reverts the change to not inject the `nvidia-persistenced` socket by default.
* #694 
* #703
> Revert #703 and #694

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
- internal/lookup/symlinks/symlink.go
This change fixes an incorrectly constructed error message in symlink resolution.
> Fix symlink resolution error message

- cmd/nvidia-ctk/runtime/configure/configure.go
This fix ensures that the default config file path for the nvidia-ctk runtime configure command is set consistently.
This bug was introduced in #686
> Fix bug in default config file path

- pkg/nvcdi/lib.go
> Fix custom config path handling

- .github/workflows/image.yaml
> [no-relnote] switch to the newer qemu artifacts image

- CHANGELOG.md
- versions.mk
These changes bump the version and update the changelog for the v1.17.5 release.
> Bump version for v1.17.5 release

- .common-ci.yml
Updated .release:staging to stage images in nvstaging. These changes are needed for the new NGC Publishing workflow.
> Updated .release:staging to stage images in nvstaging

- CHANGELOG.md
- versions.mk
These changes prepare for the v1.17.6 release.
> Bump version for v1.17.6 release

- CHANGELOG.md
- versions.mk
This change prepares for the v1.17.7 release.
> Bump release v1.17.7

- internal/discover/mounts.go
- internal/discover/mounts_test.go
> Edit discover.mounts to have a deterministic output

- internal/discover/mounts.go
- internal/discover/mounts_test.go
> [release-1.17] Edit discover.mounts to have a deterministic output

- internal/modifier/discover_test.go
Fix unit tests for 007faf84913b940afc876e1843391429e2979575
> Fix unit tests

- pkg/nvcdi/full-gpu-nvml.go
- pkg/nvcdi/lib-nvml.go
- pkg/nvcdi/lib-nvml_test.go
- pkg/nvcdi/mig-device-nvml.go
These changes fix a bug in CDI spec generation introduced in #1166
where device handles become invalid when nvml is shutdown and initialized
again. Here we explicitly store UUIDs and use these to query the
device handles when generating the CDI specification.
> [no-relnote] Fix CDI spec generation

- tests/e2e/nvidia-container-toolkit_test.go
This backports a test from #1327
> [no-relnote] Add basic regression test for nvidiascape
