- cmd/nvidia-ctk/system/create-device-nodes/create-device-nodes.go
Fixed a minor spelling error inside `nvidia-ctk system create-device-nodes`.
> chore(cmd): Fixing minor spelling error.

- CHANGELOG.md
- versions.mk
Reverts NVIDIA/nvidia-container-toolkit#323
The `nvidia/cuda:12.3.2*` images are not yet available.
See https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=12.3.
> Revert "chore: Update CUDA base image to 12.3.2"

- Makefile
- internal/cuda/cuda.go
- internal/dxcore/dxcore.go
These changes allow the build and test targets to run successfully on Darwin.
> Fix build and tests targets on darwin

- CHANGELOG.md
- cmd/nvidia-ctk/runtime/configure/configure.go
- versions.mk
This bumps the version to `v1.14.5` and cherry picks the following changes from `main`:
* [!541](https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/541): Fix `nvidia-ctk runtime configure --cdi.enabled` for Docker.
> Cherry-pick changes for v1.14.5

- internal/info/proc/devices/builder.go
- internal/info/proc/devices/devices.go
- internal/info/proc/devices/devices_mock.go
- internal/info/proc/devices/devices_test.go
- internal/system/nvdevices/devices_test.go
This PR fixes #324
It checks the NVIDIA Devices struct constructed from `/proc/devices` for both `nvidia` and `nvidia-frontend` to retrieve the major number.
This enables support for newer driver versions ( >= 550.40 drivers) where the module was renamed while still allowing this to detect the kernel module not being loaded.
> Support nvidia and nvidia-frontend names when getting device major

- CHANGELOG.md
- cmd/nvidia-ctk/cdi/generate/generate.go
- pkg/nvcdi/api.go
- pkg/nvcdi/full-gpu-nvml.go
- pkg/nvcdi/gds.go
- pkg/nvcdi/lib-csv.go
- pkg/nvcdi/lib-nvml.go
- pkg/nvcdi/lib-wsl.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/management.go
- pkg/nvcdi/mig-device-nvml.go
- pkg/nvcdi/mofed.go
- pkg/nvcdi/namer.go
- pkg/nvcdi/options.go
This means that devices can be selected by index OR uuid from the same spec:
```
./nvidia-ctk cdi generate 2>/dev/null | grep name
name: "0"
name: GPU-4cf8db2d-06c0-7d70-1a51-e59b25b2c16c
name: "1"
name: GPU-4404041a-04cf-1ccf-9e70-f139a9b1e23c
name: "2"
name: GPU-79a2ba02-a537-ccbf-2965-8e9d90c0bd54
name: "3"
name: GPU-662077db-fa3f-0d8f-9502-21ab0ef058a2
name: "4"
name: GPU-ec9d53cc-125d-d4a3-9687-304df8eb4749
name: "5"
name: GPU-3eb87630-93d5-b2b6-b8ff-9b359caf4ee2
name: "6"
name: GPU-8216274a-c05d-def0-af18-c74647300267
name: "7"
name: GPU-b1028956-cfa2-0990-bf4a-5da9abb51763
name: all
```
Looking at the generated spec we see that the `0` and `GPU-4cf8db2d-06c0-7d70-1a51-e59b25b2c16c` devices have the same spec:
```
- containerEdits:
deviceNodes:
- path: /dev/nvidia0
- path: …
```
> Allow multiple naming strategies when generating CDI specification

- CHANGELOG.md
- internal/info/proc/devices/builder.go
- internal/info/proc/devices/devices.go
- internal/info/proc/devices/devices_mock.go
- internal/info/proc/devices/devices_test.go
- internal/system/nvdevices/devices_test.go
With newer driver versions the nvidia-frontend name in /proc/devices was replaced with nvidia. This change allows both nvidia and nvidia-frontend to be used to extract the expected device major (195).
This cherry-picks the changes from #330
> Support both nvidia and nvidia-frontend when extracting major

- cmd/nvidia-container-runtime-hook/container_config.go
- cmd/nvidia-container-runtime-hook/main.go
```
docker run -it \
-e NVIDIA_IMEX_CHANNELS=0,1,2047 \
-e NVIDIA_VISIBLE_DEVICES=0 \
ubuntu:22.04 bash -c "ls -la /dev/nvidia*"
crw-rw-rw- 1 root root 504,   0 Jan 18 12:59 /dev/nvidia-uvm
crw-rw-rw- 1 root root 504,   1 Jan 18 12:59 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Jan 18 12:59 /dev/nvidia0
crw-rw-rw- 1 root root 195, 255 Jan 18 12:59 /dev/nvidiactl
/dev/nvidia-caps-imex-channels:
total 0
drwxr-xr-x 2 root root       100 Jan 18 21:32 .
drwxr-xr-x 6 root root       460 Jan 18 21:32 ..
crw-rw-rw- 1 root root 508,    0 Jan 18 19:11 channel0
crw-rw-rw- 1 root root 508,    1 Jan 18 19:11 channel1
crw-rw-rw- 1 root root 508, 2047 Jan 18 19:13 channel2047
```
> Add imex support

- CHANGELOG.md
- cmd/nvidia-container-runtime-hook/container_config.go
- cmd/nvidia-container-runtime-hook/main.go
- versions.mk
This cherry-picks the following changes to the release-1.14 branch:
* #375 -- Add IMEX support
And bumps the version to v1.14.6
This requires https://github.com/NVIDIA/libnvidia-container/pull/243
> Cherry pick v1.14.6

- internal/info/proc/devices/devices.go
We missed to add the same fallback logic to the Exists method as was added to the Get method.
The gpu-operator-validator container uses the Exists method to assert the presence of `/dev/(nvidia|nvidia-frontend)`
> [R550 driver support] add fallback logic to device.Exists(name)

- .common-ci.yml
- .github/workflows/image.yaml
- .gitlab-ci.yml
- .nvidia-ci.yml
- CHANGELOG.md
- build/container/Makefile
- build/container/multi-arch.mk
Centos7 is almost EOL and from the point of view of the container-toolkit, we already include the centos7 packages in the ubi8 image.
This change removes the centos7 images from the release process.
Note that we still use centos7 to build our RPM packages to ensure a wider compatibility.
> Remove centos7 container-toolkit image

- .github/dependabot.yml
The actions for publishing the pages need to be updated on the `gh-pages` branch.
> Add dependabot for gh-pages branches

- .github/workflows/image.yaml
For non-fork builds (e.g. dependabot) we don't disable multi-arch builds.
This change adds finer control.
> Allow finer control of pushing images

- internal/dxcore/dxcore.c
D3DKMTEnumAdapters3 is required to enumerate MCDM compute-only adapters
> Use D3DKMTEnumAdapters3 for adapter enumeration

- CHANGELOG.md
- pkg/nvcdi/lib.go
This change ensures taht NVIDIA_VISIBLE_DEVICES=void is included in generated CDI specs. This prevents the NVIDIA Container Runtime Hook from injecting devices if NVIDIA_VISIBLE_DEVICES=all is set.
> Add NVIDIA_VISIBLE_DEVICES=void to CDI specs

- Makefile
Before the change:
```
docker run \
--rm \
-ti \
-e GOCACHE=/tmp/.cache/go \
-e GOMODCACHE=/tmp/.cache/gomod \
-v /Users/elezar/src/container-toolkit:/work \
-w /work \
--user $(id -u):$(id -g) \
ghcr.io/nvidia/k8s-test-infra:devel-go1.20.5
I have no name!@bf871339fa93:/work$ make check
golangci-lint run ./...
2024/03/15 06:48:53 failed to initialize build cache at /.cache/golangci-lint: mkdir /.cache: permission denied
make: *** [Makefile:91: golangci-lint] Error 1
I have no name!@bf871339fa93:/work$```
```
After the change:
```
➜  container-toolkit git:(fix-golangci-lint-in-shell) ✗ make .shell
docker run \
--rm \
-ti \
-e GOCACHE=/tmp/.cache/go \
-e GOMODCACHE=/tmp/.cache/gomod \
-e GOLANGCI_LINT_CACHE=/tmp/.cache/golangci-lint \
-v /Users/elezar/src/container-toolkit:/work \
-w /work …
> Add GOLANGCI_LINT_CACHE to docker make targets

- cmd/nvidia-container-runtime/README.md
Download Ubuntu link expired, so fix it.
> fix doc link

- cmd/nvidia-ctk/config/config.go
- internal/config/config.go
- internal/config/features.go
- internal/modifier/gated.go
This change adds an nvidia-container-runtime.features config that allows individual features to be toggled at a global level. Each feature can (by default) be controlled by an environment variable.
The GDS, MOFED, NVSWITCH, and GDRCOPY features are examples of such features.
Upcoming features that may require an include `.so` symlink creation in #326
> Add support for feature flags

- internal/modifier/graphics.go
- internal/runtime/runtime.go
- internal/runtime/runtime_factory.go
- internal/runtime/runtime_factory_test.go
This allows for testing through injection of the driver root.
> Create root.Driver instance at first usage

- cmd/nvidia-ctk/cdi/generate/generate.go
- internal/discover/graphics.go
- internal/lookup/root/options.go
- internal/lookup/root/root.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/options.go
This changes adds a `Configs()` method to the Driver root abstraction that can be used to locate config files.
In addition a `--config-search-path` option is added to the `nvidia-ctk cdi generate` command to allow this to be overridden.
> Add config search path option to driver root

- internal/lookup/root/root.go
When running nvidia-ctk on a system that uses a custom XDG_DATA_DIRS environment variable value, the configuration files for `glvnd`, `vulkan`, and `egl` fail to get passed through from the host to the container. Reading from XDG_DATA_DIRS instead of hardcoding the default value allows for finding said files so they can be mounted in the container.
> Use XDG_DATA_DIRS instead of hardcoding /usr/share

- .github/dependabot.yml
This change also changes the maintenance branch to `release-1.15` over `release-1.14` since `v1.15.0` has been released.
If we decide to continue supporting `v1.14.x` with updates we can reactivate this.
> Update maintenance dependabot rule

- pkg/nvcdi/lib-nvml.go
Migrated from https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/521
> Get device specs by Identifier

- cmd/nvidia-ctk/config/config.go
- cmd/nvidia-ctk/config/config_test.go
This change switches to using `:` as the separator for slices when calling `nvidia-ctk config --set`. This works around an issue with the handling of string-slice arguments in the `urfave/cli` module.
For example, running:
```
nvidia-ctk config --set nvidia-container-runtime.runtimes=some:list:of:runtimes
```
yields:
```
runtimes = ["some", "list", "of", "runtimes"]
```
Fixes #466
> Use : as a config --set slice separator

- cmd/nvidia-ctk/runtime/configure/configure.go
- pkg/config/engine/api.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/config_v2.go
- pkg/config/engine/containerd/config_v2_test.go
- pkg/config/engine/containerd/toml.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/docker/docker.go
- tools/container/container.go
- tools/container/containerd/containerd.go
- tools/container/containerd/containerd_test.go
This change allows for the containerd configuration using the `nvidia-ctk` CLI as well as the toolkit container to set additional configuration options. This can be used, for example, to specify the value of `SystemdCgroup` explicitly.
For example:
```
./nvidia-ctk runtime configure --runtime=containerd --dry-run --runtime-config-override="{\"options\": {\"SystemdCgroup\": true}}"
INFO[0000] Config file does not exist; using empty config
version = 2
[plugins]
[plugins."io.containerd.grpc.v1.cri"]
[plugins."io.containerd.grpc.v1.cri".containerd]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
privileged_without_host_devices = false
runtime_engine = ""
runtime_root = ""
runtime_type = "io.containerd.runc.v2" …
```
> Add option to set additional containerd configs per runtime

- pkg/nvcdi/spec/builder.go
- pkg/nvcdi/spec/set-minimum-version.go
- pkg/nvcdi/spec/spec.go
- pkg/nvcdi/spec/spec_test.go
This change allows an in-memory spec to have its minimum version set on save.
This ensures that this version is updated for subsequent transforms such as root edits.
> Set mininum spec version on save

- pkg/nvcdi/transform/root/driver-root.go
- pkg/nvcdi/transform/root/driver-root_test.go
- tools/container/toolkit/toolkit.go
This adds support for using the toolkit container in environments where the "driverRoot" does not represent a chrootable filesystem.
For example, if the NVIDIA driver libraries are available at `/opt/nvidia/driver` on the host, but the device nodes are created at `/dev` on the host. Assuming these are mounted readOnly as follows into the toolkit container:
* `/opt/nvidia/driver` -> `/driver-root` 
* `/` -> `/host`
Setting the following envvars:
* `NVIDIA_DRIVER_ROOT=/opt/nvidia/driver`
* `DRIVER_ROOT_CTR_PATH=/driver-root`
* `NVIDIA_DEV_ROOT=/`
* `DEV_ROOT_CRT_PATH=/host`
will allow the CDI specification generation to complete and generate a valid CDI spec.
See https://github.com/NVIDIA/nvidia-container-toolkit/issues/209#issuecomment-1943441883
> Add dev-root option to toolkit container

- pkg/nvcdi/spec/builder.go
Although the nvidia-ctk cdi generate command generates specs with 644 permissions, the nvidia-ctk cdi transform commands do not. This change sets the default permissions to 600 instead of 644.
> Set default CDI spec permissions to 644

- go.mod
- go.sum
- vendor/modules.txt
Ths included https://github.com/xrash/smetrics/pull/11
> Bump github.com/xrash/smetrics to v0.0.0-20240521201337-686a1a2994c1

- deployments/container/Makefile
Tools such as oc mirror do not support the provenence metadata added to the image manifests with newer docker buildx versions.
This change disables the addition of provenance information.
> Remove provenance information from image manifests

- cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go
This change ensures that the created /etc/ld.so.conf.d file has a higher priority to ensure that the injected libraries take precendence.
For example:
```
ls -l /etc/ld.so.conf.d/
total 48
-rw-r--r--. 1 root root  27 Mar 16 03:23 00-cuda-compat.conf
-rw-r--r--. 1 root root  75 Jun  4 10:37 00-nvcr-XXXXXX.conf
-rw-r--r--. 1 root root  42 Aug 16  2023 000_cuda.conf
-rw-r--r--. 1 root root  45 Aug 16  2023 988_cuda-12.conf
-rw-r--r--. 1 root root 103 Mar  4  2022 aarch64-linux-gnu.conf
-rw-r--r--. 1 root root  22 Mar  9 00:31 cuda.conf
-rw-r--r--. 1 root root  96 Apr 29 07:01 deepstream.conf
-rw-r--r--. 1 root root  47 Aug 15  2023 gds-12-2.conf
-rw-r--r--. 1 root root 132 Mar  9 00:31 hpcx.conf
-rw-r--r--. 1 root root  44 Dec 16  2020 libc.conf
-rw-r--r--. 1 root root  70 Mar  9 00:25 …
```
> Increase priority of ld.so.conf.d config file

- cmd/nvidia-ctk/system/create-device-nodes/create-device-nodes.go
This change add a `--dev-root` option to the `nvidia-ctk system create-device-nodes` command. 
This allows clients such as the mig-manager to use this CLI in driver installations where the dev-root and driver-root do not match.
See https://github.com/NVIDIA/mig-parted/pull/69
> Add dev-root option to create-device-nodes

- internal/discover/graphics.go
- internal/discover/mounts-to-container-path.go
- internal/discover/mounts-to-container-path_test.go
- internal/lookup/root/root.go
This change updates how vulkan ICD files are located and how their mounts are generated. It is now possible to locate these ICD files in the driver root. e.g. at `{{ .driverRoot }}/vulkan/icd.d` istead of `{{ .driverRoot }}/etc/vulkan/icd.d`. In addition these files are always mounted to:
```
/etc/vulkan/...
```
in the container.
> Support vulkan ICD files in a driver root

- .github/workflows/release.yaml
From https://docs.github.com/en/actions/learn-github-actions/contexts#github-context 
`ref_name` will provide only the tag name
> Use ref_name on release workflow

- internal/oci/spec.go
Corrected spelling error: "OCI Srec" -> "OCI Spec"
> [no-relnote] Fixed spelling error

- internal/logger/api.go
- internal/logger/lib.go
- internal/oci/runtime.go
- internal/oci/runtime_low_level.go
- internal/oci/runtime_mock.go
- internal/oci/runtime_modifier.go
- internal/oci/runtime_path.go
- internal/oci/runtime_syscall_exec.go
- internal/runtime/runtime.go
- internal/runtime/runtime_factory.go
These changes reduce the verbosity of the logging of the NVIDIA Container Runtime -- especially for the case where no modifications are required.
See:
* https://github.com/containerd/containerd/issues/8972#issuecomment-2067595892
* https://github.com/NVIDIA/nvidia-container-toolkit/issues/511
1. Build the executable:
``` 
make cmd-nvidia-container-runtime
```
2. Create a dummy config file:
```
mkdir -p .config/nvidia-container-runtime
cat <<EOF > .config/nvidia-container-runtime/config.toml 
[nvidia-container-runtime]
log-level = "info"
runtimes = ["undefined", "missing", "runtime"]
EOF
```
3. Create a dummy runtime:
```
cat <<EOF > runtime
#!/bin/bash
echo "runtime args \$@"
EOF
chmod +x runtime
```
4. Run the NVIDIA runtime with the create command:
```
PATH=$(pwd):${PATH} …
```
> Reduce logging verbosity in NVIDIA Container Runtime

- docker/Dockerfile.rpm-yum
With the EOL of centos:7 we cannot use the repo mirrors and we therefore switch to the vault repos.
> Use centos:7 vault repos for builds

- .gitmodules
- docker/Dockerfile.rpm-yum
With the EOL of centos:7 we cannot use the repo mirrors and we therefore switch to the vault repos.
Backports #574
> Fix centos7 builds

- tools/container/operator/operator.go
This PR also helps avoid the practice of mixing pointer and value receivers for structs which is discouraged in Go
This is lint issue as reported by the GoLand IDE
```
Struct Runtimes has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 
```
> avoid using map pointers as maps are always passed by reference

- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/config_v1_test.go
- pkg/config/engine/containerd/config_v2.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/containerd/option.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/crio/crio_test.go
- pkg/config/engine/crio/option.go
- tools/container/containerd/config_v1_test.go
- tools/container/containerd/config_v2_test.go
This change updates the logic to populate the options for the nvidia runtime configs added to containerd or crio from a default runtime if this is specified and a runc entry is not found.
This allows the default runtime values for settings such as SystemdCgroup to be applied correctly.
> Extract options from default runtime if runc does not exist

- internal/platform-support/dgpu/by-path-hooks.go
- internal/platform-support/dgpu/dgpu.go
- internal/platform-support/dgpu/nvml.go
- internal/platform-support/dgpu/nvml_test.go
- internal/platform-support/dgpu/options.go
- pkg/nvcdi/full-gpu-nvml.go
- pkg/nvcdi/mig-device-nvml.go
This change refactors how we construct the discoverer for dGPU device nodes.
This allows for extension to other discovery mechanisms apart from NVML.
> Refactor dGPU device discovery

- .github/workflows/golang.yaml
- deployments/container/Dockerfile.golang
- hack/golang-version.sh
- versions.mk
This change adds logic to extract the golang version from a Dockefile.
This allows us to trigger golang updates using dependabot.
> Manage golang version with dependabot

- internal/platform-support/dgpu/nvml.go
This fixes a bug introduced in https://github.com/NVIDIA/nvidia-container-toolkit/commit/448a3853ad3b0c653209323a5cc520e664bced8a. This bug breaks CDI spec generation for MIG devices.
> [bugfix] Process error type instead of nvml.Return 

- internal/platform-support/dgpu/dgpu.go
- internal/platform-support/dgpu/nvml.go
- internal/platform-support/dgpu/nvml_test.go
- internal/platform-support/dgpu/options.go
This adds a basic test that fails without the changes of #619
Against `v1.16.0`:
```
--- FAIL: TestNewNvmlMIGDiscoverer (0.00s)
--- FAIL: TestNewNvmlMIGDiscoverer/#00 (0.00s)
nvml_test.go:161:
Error Trace:    /Users/elezar/src/container-toolkit/internal/platform-support/dgpu/nvml_test.go:161
Error:          Target error should be in err chain:
expected: ""
in chain: "error getting placement info: error getting GPU minor: <nil>"
"error getting GPU minor: <nil>"
Test:           TestNewNvmlMIGDiscoverer/#00
FAIL
```
> [no-relnotes] Add initial unit test for MIG CDI spec generation

- cmd/nvidia-ctk/runtime/configure/configure.go
This change ensures that we unnecessarily print warnings for runtimes where these configs are not applicable.
This removes the following warnings:
```
WARN[0000] Ignoring runtime-config-override flag for docker
```
See #631
> Use empty string for default runtime-config-override

- .golangci.yml
> [no-relnote] Ignore integer overflow in golangci-lint

- internal/discover/graphics.go
- internal/discover/graphics_test.go
This change ensures that the `libnvidia-allocator.so.RM_VERSION` mount is not injected BOTH by the `nvidia-container-runtime` through modifying the OCI spec AND libnvidia-container.
First injecting the mount through the OCI spec and then also following the mount logic implemented in `libnvidia-container` causes mounts to be leaked to the host when bind-propagation is enabled in a container.
To verify these changes set up the following folder:
```
$ mkdir -p /tmp/empty
```
Run the existing `nvidia` runtime:
```
$ nvidia-container-runtime --version
NVIDIA Container Runtime version 1.16.1
commit: a470818ba7d9166be282cd0039dd2fc9b0a34d73
spec: 1.2.0
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.21.9
libseccomp: 2.5.1
```
```
$ docker run --runtime=nvidia --rm -ti -e …
```
> Exclude libnvidia-allocator from graphics mounts

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
This change updates the create-symlinks hook to check whether link paths resolve in the container's filesystem. In addition the executable is updated to return an error if a link could not be created.
> Check for valid paths in create-symlinks hook

- cmd/nvidia-container-runtime-hook/main.go
- cmd/nvidia-ctk/cdi/generate/generate.go
- internal/config/features.go
- internal/discover/ipc.go
- internal/modifier/cdi.go
- internal/modifier/gated.go
- pkg/nvcdi/common-nvml.go
- pkg/nvcdi/driver-nvml.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/management.go
- pkg/nvcdi/options.go
- tools/container/toolkit/toolkit.go
This changes skips the injection of the nvidia-persistenced socket by default.
An include-persistenced-socket feature flag is added to allow the
injection of this socket to be explicitly requested.
See https://github.com/NVIDIA/libnvidia-container/pull/283
> Skip injection of nvidia-persistenced socket by default

- cmd/nvidia-container-runtime-hook/main.go
The `--no-persistenced` flag needs to be specified *after* the `configure` subcommand.
See #694
> [no-relnote] Move --no-persistenced flag to after configure

- deployments/devel/Makefile
- deployments/devel/go.mod
The `go.mod` file is currently out-of-sync as a `go mod tidy` results in a modification of the same. I've also added a make target to ensure no uncommitted changes remain after a `go mod tidy` run
> sync go.mod with go mod tidy in deployments/devel

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
This reverts commit c490baab6331ee0b7cb56f9d3c619207adb364e5, reversing changes made to 32486cf1e94acafe0b021b12506d582a22347a36.
> Revert "Merge pull request #696 from elezar/check-link-resolution"

- scripts/build-packages.sh
With the move to dependabot to udpate the libnvidia-container submodule it is no longer required to have checks in place that ensure that this is up to date when building.
In addition when re-building old commits in CI, for example we explicitly do NOT want to have this check.
> [no-relnote] Don't check for submodule changes

- versions.mk
This bumps the version to v1.16.2 for testing purposes.
The final release bump including CHANGELOG will be updated before release.
> Bump version to v1.16.2

- internal/nvsandboxutils/gpu-resources.go
This change adds a small fix for a C pointer conversion in the GetGpuResource API implementation, which was incompatible in some architectures and caused failures.
> Fix an incompatible pointer conversion in nvsandboxutils

- pkg/nvcdi/driver-nvml.go
This change adds the vdpau subfolder to the paths searched for driver libraries. This allows the libvdpau_nvidia.so.RM_VERSION library to also be discovered.
> Also search for driver libraries in vdpau

- .github/workflows/golang.yaml
- deployments/devel/go.mod
Adding the second go mod check to github Actions so we catch out-of-sync go mods before they are merged to main
This PR is a follow-up of https://github.com/NVIDIA/nvidia-container-toolkit/pull/702
> add go modules check for deployments/devel

- internal/discover/none.go
- internal/discover/symlinks.go
- internal/discover/symlinks_test.go
- internal/platform-support/dgpu/nvml_test.go
- internal/platform-support/tegra/csv.go
- internal/platform-support/tegra/symlinks.go
- pkg/nvcdi/driver-nvml.go
This change aligns the creation of symlinks under CDI with
the implementation in libnvidia-container. If the driver libraries
are present, the following symlinks are created:
* {{ .LibRoot }}/libcuda.so -> libcuda.so.1
* {{ .LibRoot }}/libnvidia-opticalflow.so -> libnvidia-opticalflow.so.1
* {{ .LibRoot }}/libGLX_indirect.so.0 -> libGLX_nvidia.so.{{ .Version }}
> Align driver symlinks with libnvidia-container

- pkg/nvcdi/lib.go
- pkg/nvcdi/management.go
This fix ensures that `nvsandboxutils` is available when generating management CDI specifications.
Without the fix:
```
./nvidia-ctk cdi generate --mode=management > /dev/null
INFO[0000] Using /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.515.105.01
WARN[0000] Ignoring error in locating libnvidia-sandboxutils.so.1: pattern libnvidia-sandboxutils.so.1 not found
64-bit library libnvidia-sandboxutils.so.1: not found
INFO[0000] Selecting /dev/nvidia-fs0 as /dev/nvidia-fs0
INFO[0000] Selecting /dev/nvidia-fs1 as /dev/nvidia-fs1
INFO[0000] Selecting /dev/nvidia-fs10 as /dev/nvidia-fs10
INFO[0000] Selecting /dev/nvidia-fs11 as /dev/nvidia-fs11
INFO[0000] Selecting /dev/nvidia-fs12 as /dev/nvidia-fs12
INFO[0000] Selecting /dev/nvidia-fs13 as /dev/nvidia-fs13
INFO[0000] Selecting /dev/nvidia-fs14 as …
```
> Ensure that nvsandboxutils is available for version

- cmd/nvidia-ctk/runtime/configure/configure.go
- internal/config/toml.go
- pkg/config/engine/api.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/config_v1_test.go
- pkg/config/engine/containerd/config_v2.go
- pkg/config/engine/containerd/config_v2_test.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/crio/crio_test.go
- pkg/config/engine/docker/docker.go
- pkg/config/engine/docker/docker_test.go
- pkg/config/engine/engine.go
- pkg/config/toml/source-cli.go
- pkg/config/toml/source.go
- tools/container/nvidia-toolkit/run.go
- tools/container/runtime/containerd/containerd.go
- tools/container/runtime/crio/crio.go
- tools/container/runtime/docker/docker.go
- tools/container/runtime/runtime.go
- tools/container/toolkit/toolkit.go
Summary of changes made in this PR:
1. In CRI-O and Containerd config engines, retrieve the container runtime config commands via the following commands:
i. `crio status config`
ii. `containerd config dump`
2. When configuring CRI-O runtime, we prioritise the runtime designated as the `default_runtime` in the config when setting up the `nvidia` runtime handler as opposed to favouring the `runc` runtime handler at all times. This is needed as vanilla cri-o packages have `crun` as the default low-level-runtime. Live-swapping the low-level runtime causes the running containers in a cluster to break
3. Add the full path of the low-level runtime to the `nvidia-container-runtime.runtimes` config value, so that `nvidia-container-runtime` binds to a low-level runtime binary that cannot be …
> Fetch current container runtime config

- internal/discover/none.go
- internal/discover/symlinks.go
- internal/discover/symlinks_test.go
- internal/platform-support/dgpu/nvml_test.go
- internal/platform-support/tegra/csv.go
- internal/platform-support/tegra/symlinks.go
- pkg/nvcdi/driver-nvml.go
This change aligns the creation of symlinks under CDI with the implementation in libnvidia-container. If the driver libraries are present, the following symlinks are created:
* {{ .LibRoot }}/libcuda.so -> libcuda.so.1
* {{ .LibRoot }}/libnvidia-opticalflow.so -> libnvidia-opticalflow.so.1
* {{ .LibRoot }}/libGLX_indirect.so.0 -> libGLX_nvidia.so.{{ .Version }}
This backports #715
> Add creation of select driver symlinks to CDI spec

- Makefile
This fixes undefined symbol errors on platforms where -z,lazy may not be the default.
This was inadvertently removed in #333 and replaced with `-Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files` which seems to be equivalent on some systems.
> Add -z,lazy to LDFLAGS

- pkg/nvcdi/management.go
This changes adds IMEX channel devices to the management CDI spec.
Note that these devices nodes have to exist at the point of spec generation.
Part of https://github.com/NVIDIA/cloud-native-team/issues/113
> Add imex channels to management CDI spec

- .golangci.yml
- CHANGELOG.md
- cmd/nvidia-ctk/runtime/configure/configure.go
- internal/platform-support/tegra/csv.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/docker/docker.go
- tools/container/nvidia-toolkit/run.go
i) Fix some typo errors
ii) Remove redundant import aliases
iii) Remove `deadline`, which is an invalid field in `golangci-lint.yml`, and replace it with `timeout`
> minor cleanup and improvements

- internal/config/features.go
- internal/config/image/cuda_image.go
- internal/modifier/gated.go
This change removes the ability to set the per-container opt-in features for GDS and MOFED, for example.
This functionality added in https://github.com/NVIDIA/nvidia-container-toolkit/pull/362 was not publicly documented.
> Remove ability to set per-container features in the config file

- cmd/nvidia-container-runtime-hook/main.go
- internal/config/features.go
- tools/container/toolkit/toolkit.go
This change adds a `disableIMEXChannelCreation` feature flag that allows the `--no-create-imex-channels` option added  in https://github.com/NVIDIA/libnvidia-container/pull/286 to be toggled.
This allows IMEX channels to be exposed in environment where they are expected to be created up front.
See also https://github.com/NVIDIA/k8s-device-plugin/pull/985
> Add disableIMEXChannelCreation feature flag

- cmd/nvidia-container-runtime-hook/container_config.go
- cmd/nvidia-container-runtime-hook/container_config_test.go
- cmd/nvidia-container-runtime-hook/main.go
- internal/config/image/builder.go
- internal/config/image/cuda_image.go
- internal/config/image/cuda_image_test.go
- internal/config/image/envvars.go
- internal/modifier/cdi.go
- internal/modifier/csv.go
- internal/modifier/gated.go
- internal/modifier/graphics.go
- pkg/nvcdi/lib.go
This allows IMEX channels to be requested as volume mounts in addition to the `NVIDIA_IMEX_CHANNELS` environment variable.
See https://github.com/NVIDIA/k8s-device-plugin/pull/985 where this is used in the NVIDIA Device Plugin when the `deviceListStrategy` is set to `volume-mounts`.
> Allow IMEX channel requests by volume mount

- tools/container/runtime/runtime.go
This change ensures that the toolkit works with older versions of the GPU Operator where runtime-specific envvars are used to set options such as the config file location.
The support for these envvars was removed in #686
> Add aliases for runtime-specific envvars

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
This change removes support for specifying csv-filenames when
calling the create-symlinks hook. This is no longer required
as tegra-based systems generate hooks with `--link` arguments.
This also allows the hook to better serve as a reference implementation
for upstream projects wanting to implement a set of standard CDI hooks.
> Remove csv filenames support

- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/crio/crio.go
- pkg/config/toml/list.go
- pkg/config/toml/source.go
When running the latest toolkit on an OpenShift 4.14 cluster, we noticed that the `crio status config` command was failing with the following error:
```
time="2024-10-23T00:49:22Z" level=error msg="error running nvidia-toolkit: unable to determine runtime options: unable to load crio config: failed to run command chroot [/host crio status config]: exit status 1"
```
On further investigation, we found that in CRIO versions/K8s Cluster older v1.28, the `crio-status` command was used to retrieve crio container runtime config as opposed to the `status` subcommand of the crio binary.  
Since we need to support clusters as old as OCP `4.12` i.e `cri-o v1.27`, I thought it would be a good idea to add support fallback CLI commands to the tomlCLISource. This way, if `crio status config` fails, we …
> [TOML ConfigSource] add support for executing fallback CLI commands

- pkg/nvcdi/lib-nvml.go
This change fixes a bug when using just-in-time CDI spec generation for the NVIDIA Container Runtime for specific devices (i.e. not 'all').
Instead of unconditionally using the default nvsandboxutils library -- leading
to errors due to undefined symbols -- we check whether the library can be
properly initialised before continuing.
The functionality was added in https://github.com/NVIDIA/nvidia-container-toolkit/pull/629
Before this change:
```
$ docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=runtime.nvidia.com/gpu=0 ubuntu nvidia-smi -L
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: /home/elezar/src/container-toolkit/nvidia-container-runtime did not terminate successfully: exit status 127: …
```
> Fix bug when using just-in-time CDI spec generation

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks_test.go
- internal/lookup/symlinks/symlink.go
This change updates the create-symlink hook to be equivalent to
```
ln -f -s target link
```
This ensures that links are updated even if they exist in the container being run.
> Force creation of symlinks in create-symlink hook

- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks.go
- cmd/nvidia-cdi-hook/create-symlinks/create-symlinks_test.go
- internal/lookup/symlinks/symlink.go
This change updates the create-symlink hook to be equivalent to `ln -f -s target link`
This ensures that links are updated even if they exist in the container being run.
This backports #773
> Force symlink creation in create-symlink hook

- tools/container/runtime/containerd/containerd.go
- tools/container/runtime/crio/crio.go
- tools/container/runtime/docker/docker.go
This change ensures that we fall back to the previous behaviour of reading the existing config from the specified config file if extracting the current config from the command line fails. This fixes use cases where the containerd / crio executables are not available.
> Fallback to file for runtime config

- internal/config/image/cuda_image.go
- internal/config/image/cuda_image_test.go
For legacy images (images with a CUDA_VERSION set but no CUDA_REQUIRES set), the default behaviour for device envvars is to treat non-existence as all.
This change ensures that the NVIDIA_IMEX_CHANNELS envvar is not treated in the same way, instead returning no devices if the envvar is not set.
See #797
> Fix NVIDIA_IMEX_CHANNELS handling on legacy images

- cmd/nvidia-container-runtime-hook/container_config.go
- cmd/nvidia-container-runtime-hook/container_config_test.go
- cmd/nvidia-container-runtime-hook/hook_config.go
- cmd/nvidia-container-runtime-hook/hook_config_test.go
- cmd/nvidia-container-runtime-hook/main.go
- internal/config/cli.go
- internal/config/cli_test.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/features.go
- internal/config/hook.go
- internal/config/runtime.go
- internal/config/toml.go
- internal/config/toml_test.go
- tools/container/toolkit/toolkit_test.go
This change only allows host-relative LDConfig paths (i.e. the `nvidia-container-cli.ldconfig` setting starts with an `@`)
An `allow-ldconfig-from-container` feature flag is added to allow for this
the default behaviour to be changed.
This feature can be toggled by running:
```
sudo nvidia-ctk config --in-place --set features.allow-ldconfig-from-container=true
```
or by including `allow-config-from-container` in the `NVIDIA_CONTAINER_TOOLKIT_OPT_IN_FEATURES` envvar.
> Only allow host-relative LDConfig paths

- cmd/nvidia-ctk/system/create-dev-char-symlinks/create-dev-char-symlinks.go
1 Use simple grammar in fsnotify package.
```
This makes checking events a lot easier; for example:
if event.Op&Write == Write && !(event.Op&Remove == Remove) {
}
Becomes:
if event.Has(Write) && !event.Has(Remove) {
}
``` 
According [fsnotify notes](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0)
2.
Fix Remove event.
> Fix fsnotify.Remove logic function.

- internal/system/nvdevices/devices.go
- internal/system/nvdevices/mknod.go
This changes fixes the TestCreateControlDevices test on systems where device nodes exist.
> Fix create-device-node test when devices exist

- cmd/nvidia-ctk/cdi/generate/generate.go
- pkg/nvcdi/api.go
- pkg/nvcdi/lib-imex.go
- pkg/nvcdi/lib-imex_test.go
- pkg/nvcdi/lib-nvml.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/mode.go
- pkg/nvcdi/options.go
- tools/container/toolkit/toolkit_test.go
This change adds a imex mode to CDI spec generation. This mode detected generates CDI specifications for existing IMEX channels. By default these devices have the fully qualified CDI device names:
`nvidia.com/imex-channel={{ .ID }}`
> Add imex mode to CDI spec generation

- cmd/nvidia-ctk/system/create-dev-char-symlinks/create-dev-char-symlinks.go
- go.mod
This removes the untested watch option from the
nvidia-ctk system create-dev-char-symlinks command.
This also removes the direct dependency on fsnotify.
> Remove watch option from create-dev-char-symlinks

- pkg/config/engine/containerd/config.go
- pkg/config/engine/containerd/config_test.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/config_v1_test.go
- pkg/config/engine/containerd/config_v2_test.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/containerd/option.go
- pkg/config/engine/docker/docker.go
- pkg/config/toml/source-map.go
- pkg/config/toml/source-string.go
- pkg/config/toml/source.go
- tools/container/runtime/containerd/config_v1_test.go
- tools/container/runtime/containerd/config_v2_test.go
- tools/container/runtime/containerd/containerd.go
With the release of containerd 2.0 comes a new default config version. This PR attempts to support the new version 3 of the containerd configuration.
Version 3 is fairly similar to 2 and for all intents and purposes, a valid version 3 config is a valid version 2 config (bar the version of course). So for now I've just gone and copied the V2 logic and changed things here and there.
> Add support for containerd v3 configs

- pkg/config/engine/containerd/config.go
- pkg/config/engine/containerd/config_test.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/containerd/config_v1_test.go
- pkg/config/engine/containerd/config_v2_test.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/containerd/option.go
- pkg/config/engine/docker/docker.go
- pkg/config/toml/source-map.go
- pkg/config/toml/source-string.go
- pkg/config/toml/source.go
- tools/container/runtime/containerd/config_v1_test.go
- tools/container/runtime/containerd/config_v2_test.go
- tools/container/runtime/containerd/containerd.go
This change adds support for containerd configs with version=3.
From the perspective of the runtime configuration the contents of the
config are the same. This means that we just have to load the new
version and ensure that this is propagated to the generated config.
The one exception is that the v3 config also requires a switch to the `io.containerd.cri.v1.runtime`
CRI runtime plugin. See:
https://github.com/containerd/containerd/blob/v2.0.0/docs/PLUGINS.md
https://github.com/containerd/containerd/issues/10132
Note that we still use a default config of version=2 since we need to
ensure compatibility with older containerd versions (1.6.x and 1.7.x).
This is a backport of #805
> Add support for containerd version 3 config

- deployments/container/Dockerfile.ubi8
- deployments/container/Dockerfile.ubuntu
This removes the following warnings when building the docker containers:
```
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 65)
- UndefinedVar: Usage of undefined variable '$VERSION' (line 81)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 18)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 39)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 40)
```
> [no-relnote] Fix Dockerfile lint issues

- internal/modifier/list.go
- internal/runtime/runtime_factory.go
In CSV mode the CSV files at /etc/nvidia-container-runtime/host-files-for-container.d/ should be the source of truth for container modifications. This change skips graphics modifications to a container. This prevents conflicts when handling files such as vulkan icd files which are already defined in the CSV file.
Applying both modifications leads to errors such as:
```
time="2025-01-21T18:55:11Z" level=info msg="Symlinking /var/lib/docker/overlay2/8592b399d9308cdbef42010765f81af3f921ed86aa07c7e686b59f1e72fc3e2d/merged/etc/vulkan/icd.d/nvidia_icd.json to /usr/lib/aarch64-linux-gnu/nvidia/nvidia_icd.json"
time="2025-01-21T18:55:11Z" level=error msg="failed to create link [/usr/lib/aarch64-linux-gnu/nvidia/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json]: failed to create symlink: failed …
```
> Skip graphics modifier in CSV mode

- internal/modifier/list.go
- internal/runtime/runtime_factory.go
In CSV mode the CSV files at `/etc/nvidia-container-runtime/host-files-for-container.d/` should be the source of truth for container modifications. This change skips graphics modifications to a container. This prevents conflicts when handling files such as vulkan icd files which are already defined in the CSV file.
Applying both modifications leads to errors such as:
```
time="2025-01-21T18:55:11Z" level=info msg="Symlinking /var/lib/docker/overlay2/8592b399d9308cdbef42010765f81af3f921ed86aa07c7e686b59f1e72fc3e2d/merged/etc/vulkan/icd.d/nvidia_icd.json to /usr/lib/aarch64-linux-gnu/nvidia/nvidia_icd.json"
time="2025-01-21T18:55:11Z" level=error msg="failed to create link [/usr/lib/aarch64-linux-gnu/nvidia/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json]: failed to create symlink: failed …
```
> Skip graphics for csv

- cmd/nvidia-container-runtime-hook/main.go
- internal/config/features.go
This change passes the `--no-cntlibs` argument to the `nvidia-container-cli` from the nvidia-container-runtime-hook to disable overwriting host drivers with the compat libs from a container being started.
Note that this may be a breaking change for some applications. For that reason an `allow-cuda-compat-libs-from-container` feature flag is provided to opt-in to the previous behaviour.
>  Disable mounting of compat libs from container by default

- .github/workflows/image.yaml
This PR fixes the recent segfault errors that have been showing up in the CI's multi-arch docker builds lately.  This [comment](https://github.com/tonistiigi/binfmt/issues/215#issuecomment-2613004741) summarises the root cause well.
Since our linux runners have picked up the newer kernels, the old qemu versions from the default `tonistiigi/binfmt:latest` are no longer compatible. Moreover, the `latest` tag hasn't been updated in over two years. So we switch to the `master` tag instead which is regularly maintained and is based on qemu 9.2.0 instead
P.S: If you're wondering why the `setup-qemu-action` doesn't pick up the `master` tag instead, the maintainers have already responded to that question.  See [here](https://github.com/tonistiigi/binfmt/issues/165#issuecomment-1996882334)
So far, …
> [no-relnote] switch to the newer qemu artifacts image

- cmd/nvidia-ctk-installer/container/container.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/config_v1_test.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/config_v2_test.go
- cmd/nvidia-ctk-installer/container/runtime/runtime.go
- cmd/nvidia-ctk-installer/container/toolkit/toolkit.go
- cmd/nvidia-ctk-installer/container/toolkit/toolkit_test.go
- cmd/nvidia-ctk-installer/main.go
- cmd/nvidia-ctk-installer/main_test.go
- cmd/nvidia-ctk/runtime/configure/configure.go
- pkg/config/engine/api.go
- pkg/config/engine/containerd/config.go
- pkg/config/engine/containerd/config_v1.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/docker/docker.go
These changes add an option to enable CDI in container engines (containerd, crio, docker) from the toolkit contaienr.
This can be triggered through the `--enable-cdi-in-runtime` command line option or `RUNTIME_ENABLE_CDI` environment variable.
> Add option in toolkit container to enable CDI in runtime

- .github/workflows/image.yaml
Since we have switched to using pr-copy-bot (#896), we need to update how we determine whether PRs are created.
> Fix detection of PRs

- internal/modifier/csv.go
- internal/modifier/csv_test.go
- internal/modifier/hook_remover.go
- internal/runtime/runtime_factory.go
- internal/runtime/runtime_factory_test.go
- tests/e2e/nvidia-container-toolkit_test.go
This changes ensures that the cdi modifier also removes the NVIDIA
Container Runtime Hook from the incoming spec. This aligns with what is
done for CSV modifications and prevents an error when starting the
container.
> Allow cdi mode to work with --gpus flag

- internal/modifier/csv.go
- internal/modifier/csv_test.go
- internal/modifier/hook_remover.go
- internal/runtime/runtime_factory.go
- internal/runtime/runtime_factory_test.go
> Remove nvidia container runtime hook in cdi mode

- pkg/nvcdi/lib.go
Repeated calls to nvsandboxutils.Init and Shutdown are causing segmentation violations. Here we disabled nvsandbox utils unless explicitly specified.
We will reenable the interaction with this library once the required checks and tests are in place to ensure that we don't introduce breakages.
This was tested by updating `nvidia-ctk cdi generate` to allow for multiple modes and validating that removing this initialisation fixes the failure.
> Disable nvsandboxutils in nvcdi API

- cmd/nvidia-cdi-hook/commands/commands.go
- cmd/nvidia-cdi-hook/cudacompat/container-root.go
- cmd/nvidia-cdi-hook/cudacompat/cudacompat.go
- cmd/nvidia-cdi-hook/cudacompat/cudacompat_test.go
- cmd/nvidia-ctk-installer/container/toolkit/toolkit_test.go
- cmd/nvidia-ctk/cdi/generate/generate.go
- cmd/nvidia-ctk/cdi/generate/generate_test.go
- internal/config/features.go
- internal/discover/compat_libs.go
- internal/modifier/gated.go
- internal/runtime/runtime_factory.go
- pkg/nvcdi/driver-nvml.go
- tests/e2e/nvidia-container-toolkit_test.go
- vendor/github.com/NVIDIA/go-nvml/pkg/nvml/mock/dgxa100/dgxa100.go
- vendor/github.com/NVIDIA/go-nvml/pkg/nvml/mock/dgxa100/mig-profile.go
- vendor/modules.txt
With #877 the default behaviour of the NVIDIA Container Runtime / NVIDIA Container Runtime Hook was changed to *not* mount compat libraries from the container into the container. This removed "automatic" support for CUDA Forward compatibility.
This change attempts to address this by adding a `createContainerHook` that will create a file in `/etc/ld.so.conf.d/` in the container to ensure that the `/usr/local/cuda/compat` libraries are added to the ldcache over the libraries mounted from the host. The provided host diver version is compared to the version of the compat libraries in the container and the config update is only performed if the compat libraries are newer than the host drivers.
Note that the hook *only creates a file* in the container's file system and does not perform any …
> Add CUDA forward compatibility hook

- cmd/nvidia-container-runtime-hook/container_config.go
- internal/config/features.go
This allows the NVIDIA Container Toolkit to ignore IMEX channel requests through the NVIDIA_IMEX_CHANNELS envvar or volume mounts and ensures that the NVIDIA Container Toolkit cannot be used to provide out-of-band access to an IMEX channel by simply specifying an environment variable, possibly bypassing other checks by an orchestration system such as kubernetes.
To enable this feature add the following to the `config.toml`:
```
[features]
ignore-imex-channel-requests = true
```
This can also be done by running:
```
sudo nvidia-ctk config --set features.ignore-imex-channel-requests
```
In the case of the toolkit container ensure that the `NVIDIA_CONTAINER_TOOLKIT_OPT_IN_FEATURES` includes `ignore-imex-channel-requests`.
> Add ignore-imex-channel-requests feature flag

- pkg/nvcdi/driver-nvml.go
This change adds the nvidia-imex and nivdia-imex-ctl binaries to the list of driver binaries that are searched when using CDI.
This backports #881
> Add IMEX binaries to CDI discovery

- cmd/nvidia-ctk-installer/container/toolkit/toolkit_test.go
- pkg/nvcdi/api.go
- pkg/nvcdi/common-nvml.go
- pkg/nvcdi/driver-nvml.go
- pkg/nvcdi/hooks.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/management.go
- pkg/nvcdi/options.go
This change adds support to the nvcdi package to opt out of specific hooks.
Currently only the `enable-cuda-compat` hook is supported. This allows clients to generate a CDI spec that is compatible with older nvidia-cdi-hook CLIs.
This is required in cases where a tool such as the k8s-device-plugin or k8s-dra-driver-gpu needs to generate a CDI specification for a version of the NVIDIA Container Toolkit that does not support this hook.
> Allow enable-cuda-compat hook to be disabled in CDI spec generation

- scripts/Dockerfile.sign.rpm
The signing container need not be based on a legacy centos version. This change updates the signing contianer to be centos:stream9 based.
> [no-relnote] Use centos:stream9 for signing container

- internal/discover/discover.go
- internal/info/proc/devices/devices.go
- internal/ldcache/ldcache.go
- internal/lookup/locator.go
- internal/nvsandboxutils/gen/nvsandboxutils/generateapi.go
- internal/nvsandboxutils/lib.go
- internal/nvsandboxutils/mock/interface.go
- internal/nvsandboxutils/zz_generated.api.go
- internal/oci/runtime.go
- internal/oci/spec.go
- internal/requirements/constraints/constraints.go
- internal/requirements/constraints/property.go
- internal/system/nvdevices/mknod.go
- internal/system/nvmodules/cmd.go
- pkg/nvcdi/namer.go
This change ensures that the go imports are properly formatted in generated mocks (using `goimports`).
The `-rm` flag is also added to ensure that previous mocks are removed before generation.
> [no-relnotes] Update moq to use rm and goimports

- cmd/nvidia-ctk/config/config.go
- cmd/nvidia-ctk/main.go
The urfave update to v2.27.6 fixes the behaviour when disabling a separator for repeated StringSliceFlags. This change updates the nvidia-ctk config command to allow list options to be specified as comma-separated values.
For example:
```
➜  container-toolkit git:(allow-comma-separated-config-values) ✗ ./nvidia-ctk config --set nvidia-container-runtime.runtimes=foo,bar,baz | grep runtimes
runtimes = ["foo", "bar", "baz"]
➜  container-toolkit git:(allow-comma-separated-config-values) ✗ ./nvidia-ctk config --set nvidia-container-runtime.runtimes=foo:bar:baz | grep runtimes
runtimes = ["foo", "bar", "baz"]
```
> Allow nvidia-ctk config --set to accept comma-separated lists

- cmd/nvidia-cdi-hook/update-ldcache/update-ldcache.go
This change updates how the lconfig arguments are constructed. This makes the update-ldcache more robust and ensures that folders are specified last if at al.
Checks are also included for empty container roots at the start of the hook to simplify later checks.
> Fix update-ldcache arguments

- internal/discover/mounts.go
This change switches to using the WithCache decorator for mounts instead of keeping track of a cache locally.
This addresses a race condition when using the mounts structure.
Fixes #731
> Fix race condition in mounts cache

- cmd/nvidia-ctk-installer/container/container.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/containerd.go
- cmd/nvidia-ctk-installer/container/runtime/crio/crio.go
- cmd/nvidia-ctk-installer/container/runtime/runtime.go
- cmd/nvidia-ctk-installer/main.go
- cmd/nvidia-ctk/runtime/configure/configure.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/crio/crio.go
This change adds support for specifying the container runtime executable path. This can be used if, for example, there are two containerd executables and a specific one must be used.
Deploying to a k0s system with:
```
helm install gpu-operator -n gpu-operator --create-namespace \
nvidia/gpu-operator $HELM_OPTIONS \
--version=v25.3.0 \
--set toolkit.repository=ghcr.io/nvidia \
--set toolkit.version=ae385428-ubuntu20.04 \
--set toolkit.env[0].name=RUNTIME_CONFIG \
--set toolkit.env[0].value=/etc/k0s/containerd.d/nvidia.toml \
--set toolkit.env[1].name=RUNTIME_SOCKET \
--set toolkit.env[1].value=/run/k0s/containerd.sock \
--set toolkit.env[2].name=RUNTIME_EXECUTABLE_PATH \
--set toolkit.env[2].value=/var/lib/k0s/bin/containerd \
--set toolkit.env[3].name=NVIDIA_RUNTIME_NAME \
--set …
```
> Allow container runtime executable path to be specified

- docker/docker.mk
Manual build for nvidia-contaier-toolkit is necessary! It can help open source community with debug and adding new features to this magnificent utility!
Manual build correct working was tested by me on ubuntu22.04 (run docker with gpus all on different models).
> Add support for building ubuntu22.04 on amd64

- internal/discover/list.go
When constructing a list of discoverers using discover.Merge we explicitly skip `nil` discoverers to simplify usage as we don't have to explicitly check validity when processing the discoverers in the list.
> Skip nil discoverers in merge

- internal/ldcache/ldcache.go
Since we explicitly check for the architecture of the libraries in the ldcache, we need to also check the architecture flag against the ARM constants.
Fixes #1045
> Fix resolution of libs in LDCache on ARM

- internal/discover/list.go
When constructing a list of discoverers using discover.Merge we explicitly skip `nil` discoverers to simplify usage as we don't have to explicitly check validity when processing the discoverers in the list.
Backport of #1065
> [no-relnote] Skip nil discoverers in merge

- go.mod
- go.sum
- internal/info/auto_test.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/device/mig_device.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/api.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/property-extractor_mock.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/info/resolver.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mmio.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mmio/mock.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvpci/mock.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/pciids/default_pci.ids
- vendor/modules.txt
This change adds support for the detection of Thor-based systems as Tegra devices which use `csv` mode by default.
This was added to go-nvlib in https://github.com/NVIDIA/go-nvlib/pull/60
> Fix mode detection on Thor-based systems

- cmd/nvidia-container-runtime-hook/hook_config.go
- cmd/nvidia-container-runtime-hook/main.go
- cmd/nvidia-ctk-installer/main_test.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/runtime.go
- internal/config/toml_test.go
- internal/modifier/gated.go
This change adds a config option to trigger the `--cuda-compat-mode=ldconfig` option added to the `nvidia-container-cli` in https://github.com/NVIDIA/libnvidia-container/pull/307.
The `nvidia-container-runtime.modes.legacy.cuda-compat-mode` option controls the behaviour of both the `nvidia-container-runtime-hook` and the `nvidia-container-runtime`. The main motivation being that the hook-based CUDA Forward Compat support that was added as part of the v1.17.5 release requires the `nvidia-container-runtime` and as such does not work when only the Docker `--gpus` flag is specified.
```
$ cat check-compat.sh
#!/bin/bash
set -x
ldconfig -p | grep libcuda
ls -al  /usr/lib/x86_64-linux-gnu/libcuda.so*
mount | grep libcuda
```
```
$ docker run --rm -ti --gpus=all -e NVIDIA_DISABLE_REQUIRE=1 …
```
> Add nvidia-container-cli.compat-mode config option

- cmd/nvidia-container-runtime-hook/hook_config.go
- cmd/nvidia-container-runtime-hook/main.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/runtime.go
- internal/config/toml_test.go
- internal/modifier/gated.go
This change adds an nvidia-container-runtime.modes.legacy.cuda-compat-modeconfig option. This can be set to one of four values:
* ldconfig (default): the --cuda-compat-mode=ldconfig flag is passed to the nvidia-container-cli
* mount: the --cuda-compat-mode=mount flag is passed to the nvidia-conainer-cli
* disabled: the --cuda-compat-mode=disabled flag is passed to the nvidia-container-cli
* hook: the --cuda-compat-mode=disabled flag is passed to the nvidia-container-cli AND the
enable-cuda-compat hook is used to provide forward compatibility.
Note that the disable-cuda-compat-lib-hook feature flag will prevent the enable-cuda-compat
hook from being used. This change also means that the allow-cuda-compat-libs-from-container
feature flag no longer has any effect.
Backport of #1055
> Add cuda-compat-mode config option

- cmd/nvidia-cdi-hook/commands/commands.go
- cmd/nvidia-cdi-hook/main.go
- cmd/nvidia-ctk/hook/hook.go
To allow for CDI hooks to be added gradually we provide a generic no-op hook for unrecognised subcommands. This will log a warning (to STDERR) instead of erroring out.
For example:
```
$ ./nvidia-cdi-hook foo
WARN[0000] Unsupported CDI hook: foo
$ echo $?
0
$ ./nvidia-cdi-hook
WARN[0000] No CDI hook specified
$ echo $?
0
```
```
./nvidia-ctk hook foo
WARN[0000] Unsupported CDI hook: foo
$ echo $?
0
./nvidia-ctk hook
WARN[0000] No CDI hook specified
$ echo $?
0
```
> Issue warning on unsupported CDI hook

- CHANGELOG.md
This includes:
* https://github.com/NVIDIA/libnvidia-container/pull/310
* https://github.com/NVIDIA/libnvidia-container/pull/311
> Bump third_party/libnvidia-container from d26524a to caf057b

- pkg/nvcdi/api.go
- pkg/nvcdi/lib.go
- pkg/nvcdi/options.go
This change reenables nvsandboxutils for driver discovery. This was disabled due to an error in a specific driver version (v565) so as to not block the release of the DRA driver for ComputeDomains. See #935 
A feature flag to disable nvsandboxutils is also added to allow more flexibility in cases where this library causes issue.
> Reenable nvsandboxutils for driver discovery

- .github/workflows/e2e.yaml
- .github/workflows/image.yaml
Since we now use pr-copy-bot, we are not running image builds from forks and as such the required secrets for pushing to the ghcr are present.
> [no-relnote] Switch to public runners

- pkg/nvcdi/driver-wsl.go
While auditing the use of maps for deduplication of mounts, it was noticed that the driver store discoverer use for generating CDI specifications on WSL2-based systems was not properly deduplicating the input. This was not a bug as such, since the input value was already de-duplicated at another point.
This change simplifies the function to remove the buggy code.
> Minor cleanup of WSL2 CDI spec generation

- cmd/nvidia-ctk/cdi/generate/generate.go
- cmd/nvidia-ctk/cdi/list/list.go
This pull request introduces environment variable support for various CLI flags across multiple commands in the `nvidia-ctk cdi` command. 
These changes enhance configurability by allowing users to set default values for CLI flags via environment variables.
ENV VAR follows a logic of `NVIDIA_CTK_CDI_*`
> Add EnvVars option for all nvidia-ctk cdi commands

- internal/config/image/builder.go
- internal/config/image/cuda_image.go
- internal/config/image/cuda_image_test.go
- internal/info/auto_test.go
- internal/modifier/cdi.go
- internal/modifier/cdi_test.go
- internal/runtime/runtime_factory.go
Following the refactoring of device request extraction, we can now make CDI device requests consistent with other methods.
This change moves to using image.VisibleDevices instead of separate calls to CDIDevicesFromMounts and VisibleDevicesFromEnvVar. This also changes the way in which annotation requests are handled to be consistent with other mechanisms by including annotation devices in the list of VisibleDevices.
See:
* #1110 for the device request refactoring
* #1130 for making other requests consistent
> Make CDI device requests consistent with other methods

- cmd/nvidia-cdi-hook/commands/commands.go
- cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification.go
- cmd/nvidia-cdi-hook/disable-device-node-modification/disable-device-node-modification_test.go
- cmd/nvidia-cdi-hook/disable-device-node-modification/params_linux.go
- cmd/nvidia-cdi-hook/disable-device-node-modification/params_other.go
- cmd/nvidia-ctk/cdi/generate/generate_test.go
- internal/discover/hooks.go
- pkg/nvcdi/api.go
- pkg/nvcdi/driver-nvml.go
- pkg/nvcdi/lib.go
- tests/e2e/nvidia-container-toolkit_test.go
This change adds a hook to disable device node creation for FULL GPUs (i.e. non-MIG devices) or modification in a container by updating the `ModifyDeviceFiles` driver parameter.
(This does not include `nvidia-caps` devices that are required by MIG devices).
The presence of "extra" device nodes in a container are largely cosmetic since the container *should* not have the required cgroup access for the additional devices. This does not affect the device nodes on the host.
Without this change running a command like `nvidia-smi` in a creates the device nodes as follows:
```
elezar@dgx0126:~/src/container-toolkit$ docker run --rm -ti -e NVIDIA_VISIBLE_DEVICES=runtime.nvidia.com/gpu=0 --runtime=nvidia ubuntu bash -c "ls -al /dev/nvidia*; echo ""; nvidia-smi -L; echo ""; ls -al /dev/nvidia*" …
```
> Disable device node creation in CDI mode

- internal/config/image/cuda_image.go
- internal/config/image/cuda_image_test.go
- internal/modifier/cdi_test.go
- internal/modifier/csv.go
- internal/modifier/gated.go
- internal/modifier/graphics.go
- internal/modifier/graphics_test.go
The gated modifiers used to add support for GDS, Mofed, and CUDA Forward Comatibility only check the NVIDIA_VISIBLE_DEVICES envvar to determine whether GPUs are requested and modifications should be made. This means that use cases where volume mounts are used to request devices (e.g. when using the GPU Device Plugin) are not supported.
These changes make the extraction of devices for gated and graphics modifiers consistent with other methods.
Fixes: #1049
> BUGFIX: modifier: respect GPU volume-mount device requests

- cmd/nvidia-container-runtime-hook/container_config.go
- cmd/nvidia-container-runtime-hook/container_config_test.go
- cmd/nvidia-container-runtime-hook/hook_config.go
- cmd/nvidia-container-runtime-hook/hook_config_test.go
- cmd/nvidia-container-runtime-hook/main.go
- cmd/nvidia-container-runtime/main_test.go
- internal/info/auto.go
- internal/info/auto_test.go
- internal/modifier/cdi.go
- internal/modifier/cdi_test.go
- internal/runtime/runtime_factory.go
This PR changes the default behaviour of the NVIDIA Container Runtime to use an in-memory CDI specification to make changes to the incoming OCI runtime specification instead of invoking the `nvidia-container-runtime-hook` (i.e. "legacy" mode). This was previously available as an opt-in option when a user would request a CDI device using the predefined `runtime.nvidia.com/gpu` CDI device class as part of the CDI device name.
With this change, all device requests (annotations, volume mounts, environment variables) are mapped to `runtime.nvidia.com/gpu={{ .DeviceID }}` requests if they are not already CDI device requests. This means that CDI specifications for these defices are generated as the container is being created and these specifications are used to modify the incomming OCI runtime …
> Use just-in-time CDI spec generation by default in the NVIDIA Container Runtime

- cmd/nvidia-container-runtime-hook/hook_config.go
- cmd/nvidia-ctk-installer/toolkit/installer/directory.go
- cmd/nvidia-ctk-installer/toolkit/installer/executables.go
- cmd/nvidia-ctk-installer/toolkit/installer/executables_test.go
- cmd/nvidia-ctk-installer/toolkit/installer/installer.go
- cmd/nvidia-ctk-installer/toolkit/installer/installer_test.go
- cmd/nvidia-ctk-installer/toolkit/installer/libraries.go
- cmd/nvidia-ctk-installer/toolkit/installer/options.go
- cmd/nvidia-ctk-installer/toolkit/toolkit.go
- internal/config/config.go
- internal/config/config_test.go
This change allows the config file used by the `nvidia-container-runtime` and `nvidia-container-runtime-hook` to be explicitly set using an `NVIDIA_CTK_CONFIG_FILE_PATH` environment variable. This removes the need to inject a `-config` option when installing the `nvidia-contianer-runtime-hook` wrapper from the toolkit container and allows the two components to treat this consistently.
This would allow the changes of #700 to be integrated more easily.
> Add support for specifying the config file path in an environment variable

- cmd/nvidia-cdi-hook/disable-device-node-modification/params_linux.go
- tests/e2e/nvidia-container-toolkit_test.go
This patch fixes the handling of temporary files and directories in the NVIDIA container runtime hook, ensuring we don't leak tmpfs mounts when handling the params file in the container when in CDI mode. This is done by ensuring that the tmpfs mount that we create for the modified params file is created in the container's mount namespace instead of on the host.
We also add end2end tests to check for leaking of mounts.
> Fix leaking of tmpfs mount in CDI mode

- tests/e2e/nvidia-container-toolkit_test.go
- tests/e2e/runner.go
A container image could be crafted with a symbolic link in
/lib/firmware/nvidia/ that points to a location outside of the
container's root filesystem. When running such a container with the
NVIDIA Container Toolkit, this could potentially lead to files being
created on the host filesystem.
This change adds an end-to-end test to ensure that the toolkit is not
vulnerable to this kind of path traversal attack.
The test case covers two scenarios:
- When using CDI, which is the default, the test ensures that the
container runs without error and no files are created on the host.
- When using the legacy nvidia-container-runtime-hook, the test
ensures that the operation fails with a specific path error,
preventing any file creation on the host.
> [no-relnote] Add e2e test for firmware path traversal

- deployments/systemd/nvidia-cdi-refresh.service
The nvidia-cdi-refresh.service unit hardcodes the path to nvidia-smi as /usr/bin/nvidia-smi. On RPM-based distributions, this binary is often located at /usr/sbin/nvidia-smi.
This change modifies the systemd service file to check for the existence of nvidia-smi in both /usr/bin and /usr/sbin. By using the '|' prefix on the ConditionPathExists directives, we ensure that the condition is met if either path exists, making the service compatible across both DEB and RPM-based systems.
Ref: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Conditions%20and%20Asserts
> [no-relnote] fix(systemd): Support alternative nvidia-smi path in refresh service

- internal/ldconfig/ldconfig_linux.go
This change updates the proc mount when updating ldconfig to use secure join to align with the other functions.
> Use securejoin to resolve /proc

- deployments/systemd/nvidia-cdi-refresh.env
- deployments/systemd/nvidia-cdi-refresh.service
- packaging/debian/nvidia-container-toolkit-base.install
- packaging/rpm/SPECS/nvidia-container-toolkit.spec
This updates the packages to include the referenced environment file for the systemd unit files.  Additionally it switches the exec to then use a referenced variable for the cdi output.
> [no-relnote] Setup envfile for systemd services

- .github/workflows/golang.yaml
- packaging/rpm/SPECS/nvidia-container-toolkit.spec
The change from c4a9bbe6afa77998232d5fe5b8388a15121f6538 did not add the envfile to the rpm sources.
> [no-relnote] Fix rpm package definition

- tests/e2e/nvidia-container-toolkit_test.go
See https://github.com/NVIDIA/nvidia-container-toolkit/actions/runs/16471710159/job/46565012044 and https://github.com/NVIDIA/yum-packaging-nvidia-driver/issues/9#issuecomment-2467474093
> [no-relnote] Adjust test for removed driver symlink

- cmd/nvidia-ctk-installer/toolkit/toolkit_test.go
- cmd/nvidia-ctk/cdi/generate/generate_test.go
- pkg/nvcdi/driver-nvml.go
The changes in #1219 inadvertently removed the `vdpau` as an additional driver library search path.
This change adds a test and fixes this.
> [no-relnote] Readd vdpau as driver library search path

- tests/release/docker/centos8/entrypoint.sh
- tests/release/docker/fedora35/entrypoint.sh
Summary
This patch fixes an issue in the entrypoint.sh scripts for both CentOS 8 and Fedora 35 where the local YUM repository was not being used by default during test runs.
Issue
Even though the script creates a local YUM repository file (local.repo), it was configured with enabled=0, which means it is disabled by default. While yum-config-manager --enable local-repository was called, this is not always reliable in automated or minimal environments (e.g. CI containers) and may fail silently or be skipped.
As a result, any locally built RPM packages are not actually used during testing, making the local-repository setup ineffective.
Fix
Changed enabled=0 to enabled=1 directly in the .repo file to ensure it's active by default.
Set the correct baseurl using the ${LOCAL_REPO_DIRECTORY} …
> Fix:Local yum repo not enabled by default in centos8 and fedora35 entrypoints

- internal/lookup/root/root.go
- pkg/nvcdi/driver-nvml.go
- tests/e2e/nvidia-container-toolkit_test.go
Fixes:  #1215
Add a list of explicit libraries that don't share the libcuda version suffix.
This can be considered an early iteration; a future iteration should read the libraries from nvsandboxutils to avoid hardcoding the library version suffix.
* Added a list of explicit library names to be located, including `libEGL.so.1.1.0`, `libGL.so.1.7.0`, `libGLESv1_CM.so.1.2.0`, and others. These libraries are critical for the driver version being processed.
* Implemented a loop to locate each library in the list, appending found libraries to the main `libs` list and logging warnings for any missing libraries without causing errors. This ensures better visibility into missing dependencies while maintaining robustness.
> Add explicitLibs list to libs discovery

- tests/e2e/Makefile
- tests/e2e/e2e_test.go
- tests/e2e/installer.go
- tests/e2e/nvidia-container-cli_test.go
This patch adds an E2E test for the nvidia-container-cli that will allow us to catch regressions on libnvidia-container
> [no-relnote] Add E2E for libnvidia-container

- internal/modifier/gated.go
Since the logic to determine the host driver version relies on the extension of `libcuda.so.<RM_VERSION>`, this is not supported on some Tegra-based systems where the file always has the name `libcuda.so.1.1`. This means that the `enable-cuda-compat` hook should not be injected in CSV mode in the `nvidia` runtime.
> Don't inject enable-cuda-compat hook in CSV mode

- pkg/config/engine/containerd/config.go
- pkg/config/engine/containerd/config_test.go
- pkg/config/engine/crio/crio.go
- pkg/config/engine/crio/crio_test.go
This commit updates the AddRuntime() implementation for containerd and cri-o to clear the default runtime field if the runtime we are adding is currently set as the default AND setAsDefault=false.
> Cleanup default runtime in runtime config when setAsDefault=false

- cmd/nvidia-ctk/cdi/generate/generate.go
- cmd/nvidia-ctk/cdi/generate/generate_test.go
When generating CDI specs for coherent and noncoherent devices, we include CDI device annotations. This increases the minimum CDI spec version to v0.6.0 which is not as widely supported as v0.5.0 or v0.3.0.
This change removes these annotations after splitting the generated specs to produce coherent and/or non-coherent specs.
Closes #1262 
Note that since we're generating a CDI spec for `nvidia.com/gpu.coherent` devices, these are `v0.6.0` specs since `.` was only allowed in the spec from `v0.6.0`.
> Remove redundant CDI annotations

- cmd/nvidia-ctk-installer/container/runtime/containerd/config_test.go
- cmd/nvidia-ctk-installer/container/runtime/crio/config_test.go
This is a minor rework of the tests for drop-in file support to make them less verbose.
This should also reduce the diff in #1280
> [no-relnote] Pass options to setup tests

- pkg/config/toml/source-empty.go
This aims to further reduce the diff in #1280
> [no-relnote] Make pkg/config/toml.NewEmpty public

- cmd/nvidia-ctk-installer/container/container.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/config_test.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/containerd.go
- cmd/nvidia-ctk-installer/container/runtime/runtime.go
- pkg/config/engine/containerd/config_drop_in.go
- pkg/config/engine/containerd/containerd.go
- pkg/config/engine/containerd/option.go
This change adds support for drop-in files in a container. Here the user needs to set `RUNTIME_DROP_IN_CONFIG_HOST_PATH` in addition to `RUNTIME_DROP_IN_CONFIG`. In this case when updating the top-level containerd config, the imports will use the host path instead of the container path.
> Add support for drop-in config files in a container

- cmd/nvidia-ctk-installer/container/container.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/config_test.go
- pkg/config/engine/containerd/config_test.go
- pkg/config/engine/containerd/containerd.go
This change updates the drop-in file contents that the nvidia-ctk-installer creates for containerd. In addition to adding nvidia runtimes, the nvidia-ctk-installer also includes all existing configuration present in the source containerd configuration for the CRI plugin. That is, all configuration already present in the 'plugins."io.containerd.grpc.v1.cri"' section will be added to our drop-in file.
This is needed due to how containerd merges configuration from multiple files. See https://github.com/containerd/containerd/issues/5837
> Add CRI plugin config from source containerd config to drop-in file

- CHANGELOG.md
- cmd/nvidia-ctk/cdi/generate/generate_test.go
- go.mod
- go.sum
- pkg/nvcdi/api.go
- pkg/nvcdi/full-gpu-nvml.go
- pkg/nvcdi/mig-device-nvml.go
- vendor/github.com/NVIDIA/go-nvlib/pkg/nvlib/device/device.go
- vendor/modules.txt
This change bumps the `github.com/NVIDIA/go-nvlib` dependency from `v0.8.0` to `v0.8.1` to ensures that `nvidia.com/gpu.coherent` CDI specs are only generated for devices with an addressing mode of ATS.
It also disables the functionality for splitting generated CDI specifications based on device coherence by default. This was added in #1247, but due to discussions around whether coherence is an property that should be exposed, we are disabling this by default.
Note that users can opt in to the feature by running the `nvidia-ctk cdi generate` with the `--feature-flag=enable-coherent-annotations` command line flag. Alternatively the `nvidia-ctk cdi generate` command can be run with the `NVIDIA_CTK_CDI_GENERATE_FEATURE_FLAGS` enviroment set to include `"enable-coherent-annotations"` (in a …
> Disable generation of nvidia.com/gpu.[non]coherent CDI specs by default

- cmd/nvidia-cdi-hook/commands/commands.go
- cmd/nvidia-cdi-hook/main.go
- cmd/nvidia-ctk/hook/hook.go
Fixes #1225
Previously, when an unrecognized CDI hook was invoked with command-line flags, the nvidia-cdi-hook command would fail with a flag parsing error instead of gracefully handling the unsupported hook. This could cause container launch failures when CDI specifications reference hooks that are not yet supported by the current NVIDIA Container Toolkit version.
This PR enhances the error handling in nvidia-cdi-hook to gracefully handle unrecognized CDI hooks that include command-line flags. The changes ensure that:
Unrecognized hooks with flags are handled gracefully - Instead of failing with flag parsing errors, the command now issues a warning and continues
Backwards compatibility is maintained - Existing behavior for supported hooks remains unchanged
Container launches don't fail - …
> Fix handling of unrecognised CDI hooks

- .github/workflows/golang.yaml
- .github/workflows/image.yaml
This change is needed to support the breaking change merged to the nv-gha-runners GH action
See this [commit](https://github.com/nv-gha-runners/setup-artifactory-go-proxy/commit/a15ec16ff434e8ca3b0f76919f902080e66ebc14) for more details
> [nv-gha-runner-gh-action] use the updated action output

- CHANGELOG.md
- versions.mk
This bumps libnvidia-contianer from https://github.com/NVIDIA/libnvidia-container/commit/6eda4d76c8c5f8fc174e4abca83e513fb4dd63b0 to https://github.com/NVIDIA/libnvidia-container/commit/e78456a41c71d73eabf7a85d1e531a108789349b to backport the following changes:
* https://github.com/NVIDIA/libnvidia-container/pull/326
* https://github.com/NVIDIA/libnvidia-container/pull/315
> Bump third_party/libnvidia-container from 6eda4d7 to e78456a

- cmd/nvidia-ctk-installer/container/container.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/config_test.go
- cmd/nvidia-ctk-installer/container/runtime/containerd/containerd.go
- cmd/nvidia-ctk-installer/container/runtime/crio/config_test.go
- cmd/nvidia-ctk-installer/container/runtime/crio/crio.go
- cmd/nvidia-ctk-installer/container/runtime/runtime.go
By default container extracts the current config by running the `containerd config dump` command and if that fails we read the existing config file.
This change allows ordering of these sources to be defined as we do for the nvidia-ctk runtime configure command.
See #1222 where setting `RUNTIME_CONFIG_SOURCES=file` or `RUNTIME_CONFIG_SOURCES=file,command` should allow the current config to be preferred over the `containerd config dump` command.
This further allows an explicit path to be specified for the `file` config source so that there is a separation between the config file being modified by the tooling and the config used as the source for drop-in files, for example.
> Allow config sources to be specified for containerd and cri-o
